apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-a
  name: pod-a
spec:
  containers:
  - command: ["/bin/sh","-c"]
    args: ["/bin/echo 'sleeping forever' && /bin/sleep infinity"]
    image: ubuntu
    name: pod-a
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: aks-nodepool1-16761241-vmss000000
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-b
  name: pod-b
spec:
  containers:
  - command: ["/bin/sh","-c"]
    args: ["/bin/echo 'sleeping forever' && /bin/sleep infinity"]
    image: ubuntu
    name: pod-b
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: aks-engine1-16761241-vmss00001n
status: {}
---