kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dd-managed-hdd-1g
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-hdd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

