apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-a
  name: pod-a
spec:
  containers:
  - command: ["/bin/sh","-c"]
    args: ["/bin/echo 'sleeping forever' && /bin/sleep infinity"]
    image: ubuntu
    name: pod-a
  nodeName: aks-nodepool1-32922832-vmss000000
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-b
  name: pod-b
spec:
  containers:
  - command: ["/bin/sh","-c"]
    args: ["/bin/echo 'sleeping forever' && /bin/sleep infinity"]
    image: ubuntu
    name: pod-b
  nodeName: aks-nodepool1-32922832-vmss000001
---